# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pinal Bhatt's Blog
email: self@PBDesk.com
description: > # this means to ignore newlines until "baseurl:"
  Learning endeavor for ever...from the desk of Pinal Bhatt 
tagline: Learning endeavor for ever...  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
author:
  name: Pinal Bhatt
  email: self@PBDesk.io
  bio: always on learning ramp
  twitter: http://twitter.com/PBDesk

# Build settings
markdown: kramdown

gems:
  - jekyll-gist
